server:
  port: 8900
  
spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
