api:
  version: 1.0
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka
  instance:
    instance-id: ${spring.application.name}:${random-value}
    
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/evaluator
    
server:
  port: 0
